### ISSUE TITLE
node-keytar doesn't load on Linux arm64

### ISSUE THREAD

**Issue by quanglam2807** [atom/node-keytar#318]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

` require('keytar')` would be stuck on Linux arm64 system, blocking the whole Node process.

### Steps to Reproduce

```js
app.on('ready', () => {
  console.log(1);
  const keytar = require('keytar');
  console.log(2);
});
```

**Expected behavior:**

Console would log 1 then log 2.

**Actual behavior:**

Console only log 1.

**Reproduces how often:**

### Versions
node-keytar@7.0.0

### Additional Information
I tested `keytar` on macOS, Windows, Linux x64. They all worked.

This only happens on Linux arm64.

**Comment by quanglam2807** [comment]
Could it be because I compile keytar ARM64 on a X86-64 system? https://github.com/webcatalog/webcatalog-engine/blob/master/.github/workflows/linux-arm.yml

**Comment by shiftkey** [comment]
I've not tested anything related to NodeJS on Linux ARM64 so any sort of working code here would be down to sheer luck. We also don't ship any prebuilt binaries for Linux ARM64 currently so more context about how you're building things from source here would be helpful to learn more

**Comment by quanglam2807** [comment]
Thank you, @shiftkey. I'm currently using `electron-builder` which rebuilds `node-keytar` when building the Electron app. I personally don't have an ARM device as well. But a user reported this bug and I managed to reproduce it on a AWS EC2 with ARM64 processor.

**Comment by shiftkey** [comment]
Based on #319 it looks like we can already generate builds using the existing `prebuild` toolchain, so hopefully the next release will address this. I'll close this out when it's ready to try.

**Comment by shiftkey** [comment]
@quanglam2807 I've published `v7.1.0` to NPM which contains prebuild support for Linux ARM64 - hopefully this helps out with your work!

**Comment by quanglam2807** [comment]
It seems like the bug is not fixed (I tested on Raspberry Pi 400 / Ubuntu 20.10). Is there anything I can to assist with debugging?

**Comment by quanglam2807** [comment]
I just checked the log: https://github.com/webcatalog/webcatalog-engine/runs/1438066751?check_suite_focus=true

`electron-builder` uses the prebuilt binary so I don't think the bug must be somewhere else.

**Comment by quanglam2807** [comment]
I attempted to set up my project on Raspberry Pi and `No prebuilt binaries found` error occurred. I'm not sure what happened exactly.

**Comment by quanglam2807** [comment]
```
  • execute command  command=/opt/hostedtoolcache/node/12.19.0/x64/bin/node /home/runner/work/webcatalog-engine/webcatalog-engine/node_modules/prebuild-install/bin.js --platform=linux --arch=arm64 --target=10.1.5 --runtime=electron --verbose --force
                     workingDirectory=/home/runner/work/webcatalog-engine/webcatalog-engine/node_modules/keytar
  • command executed  executable=/opt/hostedtoolcache/node/12.19.0/x64/bin/node
                      errorOut=prebuild-install info begin Prebuild-install version 6.0.0
    prebuild-install info looking for cached prebuild @ /home/runner/.npm/_prebuilds/0e0657-keytar-v7.2.0-electron-v82-linux-arm64.tar.gz
    prebuild-install http request GET https://github.com/atom/node-keytar/releases/download/v7.2.0/keytar-v7.2.0-electron-v82-linux-arm64.tar.gz
    prebuild-install http 200 https://github.com/atom/node-keytar/releases/download/v7.2.0/keytar-v7.2.0-electron-v82-linux-arm64.tar.gz
    prebuild-install info downloading to @ /home/runner/.npm/_prebuilds/0e0657-keytar-v7.2.0-electron-v82-linux-arm64.tar.gz.3305-8adb79bde4c3c.tmp
    prebuild-install info renaming to @ /home/runner/.npm/_prebuilds/0e0657-keytar-v7.2.0-electron-v82-linux-arm64.tar.gz
    prebuild-install info unpacking @ /home/runner/.npm/_prebuilds/0e0657-keytar-v7.2.0-electron-v82-linux-arm64.tar.gz
    prebuild-install info unpack resolved to /home/runner/work/webcatalog-engine/webcatalog-engine/node_modules/keytar/build/Release/keytar.node
    prebuild-install info install Successfully installed prebuilt binary!
  ```

So indeed, `electron-builder` installs the correct binary.
